#ifndef ENUMS_H
#define ENUMS_H
enum retType{
    SUCCESS = 0,
    MEMORY_ERROR,
    FILE_ERROR,
    NULL_ERROR,
    NO_SUCH_FUNC,
    ALREADY_LOGINED,
    NOT_LOGINED,
    CONSIST,
    NOT_CONSIST,
    END_OF_FILE,
    ALREADY_EXIST,
    LOGIN_FAILED,
    CRYPT_ERROR,
    WRONG_PASSWORD,
    EXIT,
    WRONG_AMOUNT_OF_ARGS,
    DATE_ERROR,
    UNKNOWN_KEY,
    NO_MESSAGE_RETURN,
    NO_PERMISSION,
    MUST_BE_INT,
    NU_IS_FORBIDDEN,
    NO_ATTEMPTS,
    WRONG_LEN,
    DENIED
};

enum userState{
    LOGINED,
    ADMIN_LOGINED,
    UNLOGINED,
    SANCTIONED
};

#endif